/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kirjasto;

import org.junit.*;
import static org.junit.Assert.*;

import org.junit.Test;

import kirjasto.Main;

public class MainTest {
    @Test 
    public void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest.getGreeting(), "main should have a greeting");
    }
}
